version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\archfiery\literate-disco

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...

build_script:
  - go test -v -timeout 5s ./...
  - go test -v -bench=. ./...
