// Package liter_disco contains several data structures and algorithms written in GO
// The name literate_disco is a random name generated by GitHub
package literate_disco

const (
	VERSION = "0.0.1"
)